
platform_url = 'https://platform.risksense.com'

api_key = ''

saved_filter_name = 'My Saved Filter'

csv_output_filename = 'my_csv_report.csv'

# If you are a single-client user, leave this setting alone.
# If you are a multiclient user, uncomment setting, and specify the
# the client ID that you wish to work with.

#client_id = 12345