platform_url = 'https://platform2.risksense.com'
api_key='11ec67dc-ace2-f071-b01a-06a9a515001a:XjFOTFhzTyVEdyZfUk1Zb0NUeVNvQ1ZNKlBAXi0lZVpzJHh6N21IWmw4QWM3dE1iZzIwcHktRjBDdDExNzljcQ=='
client_id=793
slackwebookurl=""
outlookwebhookurl=""
email="thahasina.banu@risksense.com"
channelname='test1'
subscribe=false
deletechannel=true
channelstodelete=[52]
channelidtodisable=52
disablechannel=false
